Remove unused package LearnBase
The LearnBase package wasn't used.

In addition, the following error was generated:

using LearnBase : nobs
ERROR: UndefVarError: nobs not defined