Remove unused package LearnBase (#26)
* Remove unused package LearnBase

The LearnBase package wasn't used.

In addition, the following error was generated:

using LearnBase : nobs
ERROR: UndefVarError: nobs not defined

* Fix callbacks tests

* Revert "Fix callbacks tests"

This reverts commit 736743cf7397384ac9e34c5962c798e32e6f479f.