Fix protected tests (#28)
* Remove unused package LearnBase

The LearnBase package wasn't used.

In addition, the following error was generated:

using LearnBase : nobs
ERROR: UndefVarError: nobs not defined

* Fix Protected tests

Use new separate Read/Write protection.